# Generated by Django 5.2.5 on 2025-08-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_rename_categories_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ManyToManyField(
                related_name="products", to="product.category"
            ),
        ),
    ]
