name: Python Pull Request Workflow

on: [pull_request]

jobs:
  qa:
    name: Quality check
    runs-on: ubuntu-22.04
    env:
      SECRET_KEY: "django-insecure-test-key"  # Para testes do Django
      POETRY_VIRTUALENVS_CREATE: "false"     # Desativa virtualenvs extras do Poetry

    steps:
      # Checkout do código
      - uses: actions/checkout@v3

      # Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      # Instalar Poetry e dependências
      - name: Install Poetry and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      # Rodar testes Django
      - name: Test
        run: poetry run python manage.py test

      # Rodar styleguide
      - name: Wemake Python Styleguide
        uses: wemake-services/wemake-python-styleguide@0.16.0
        continue-on-error: true
        with:
          reporter: 'github-pr-review'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


